//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GameClient.rc
//
#define IDR_MAINFRAME                   128
#define IDR_WAVE1                       146
#define IDB_VIEW_BACK                   147
#define IDB_VIEW_FILL                   148
#define IDB_GAME_CARD                   149
#define IDB_JETTOM_VIEW                 150
#define IDB_SCORE_NUMBER                151
#define IDB_BT_JETTON_1000              152
#define IDB_BT_JETTON_10000             153
#define IDB_BT_JETTON_1                 154
#define IDB_BT_JETTON_10                155
#define IDB_BT_JETTON_100               156
#define IDB_BT_JETTON_100000            157
#define IDB_FRAME_R                     159
#define IDB_FRAME_L                     160
#define IDB_FRAME_M                     161
#define IDB_WIN_FLAGS                   162
#define IDC_SCORE_1                     163
#define IDC_SCORE_10                    164
#define IDC_SCORE_100000                165
#define IDC_SCORE_10000                 166
#define IDC_SCORE_1000                  167
#define IDC_SCORE_100                   168
#define IDR_WAVE2                       174
#define IDD_DLG_GAME_RECORD             177
#define IDB_BT_APPLY_BANKER             179
#define IDB_BITMAP2                     180
#define IDB_BT_CANCEL_BANKER            180
#define IDB_BITMAP1                     183
#define IDB_BT_JETTON_500               184
#define IDB_BT_JETTON_50000             185
#define IDB_BT_JETTON_500000            186
#define IDC_SCORE_500                   187
#define IDC_SCORE_50000                 188
#define IDC_SCORE_500000                189
#define IDB_BT_SCORE_MOVE_L             190
#define IDB_BT_SCORE_MOVE_R             191
#define IDB_APPLY_USER_BACK             193
#define IDB_FRAME_PING_JIA              194
#define IDB_FRAME_TONG_DIAN_PING        195
#define IDB_FRAME_XIAN_JIA              196
#define IDB_FRAME_XIAN_TIAN_WANG        197
#define IDB_FRAME_ZHUANG_JIA            198
#define IDB_FRAME_ZHUANG_TIAN_WANG      199
#define IDB_FRAME_OLD_PING_JIA          200
#define IDB_FRAME_OLD_TONG_DIAN_PING    201
#define IDB_FRAME_OLD_XIAN_JIA          202
#define IDB_FRAME_OLD_XIAN_TIAN_WANG    203
#define IDB_FRAME_OLD_ZHUANG_JIA        204
#define IDB_FRAME_OLD_ZHUANG_TIAN_WANG  205
#define IDB_GAME_END                    206
#define IDB_GAME_END_FRAME              207
#define IDB_GAME_POINT                  208
#define IDB_CHANGE_BANKER               209
#define IDB_ME_BANKER                   210
#define IDB_NO_BANKER                   211
#define IDB_BT_CANCEL_APPLY             212
#define IDB_TIME_FLAG                   213
#define IDB_ME_SCORE_NUMBER             214
#define IDB_FRAME_EVEN                  215
#define IDB_FRAME_ODD                   216
#define IDB_CLOSE_DICEBOX_1             217
#define IDB_CLOSE_DICEBOX_3             218
#define IDB_SHAKE_DICEBOX_11            219
#define IDB_SHAKE_DICEBOX_19            220
#define IDB_SHAKE_DICEBOX_22            221
#define IDB_SHAKE_DICEBOX_23            222
#define IDB_SHAKE_DICEBOX_18            223
#define IDB_SHAKE_DICEBOX_26            224
#define IDB_SHAKE_DICEBOX_24            225
#define IDB_SHAKE_DICEBOX_25            226
#define IDB_SHAKE_DICEBOX_28            227
#define IDB_SHAKE_DICEBOX_14            228
#define IDB_SHAKE_DICEBOX_15            229
#define IDB_SHAKE_DICEBOX_2             230
#define IDB_SHAKE_DICEBOX_27            231
#define IDB_SHAKE_DICEBOX_29            232
#define IDB_SHAKE_DICEBOX_4             233
#define IDB_SHAKE_DICEBOX_3             234
#define IDB_SHAKE_DICEBOX_20            235
#define IDB_SHAKE_DICEBOX_16            236
#define IDB_CLOSE_DICEBOX_11            237
#define IDB_CLOSE_DICEBOX_4             238
#define IDB_CLOSE_DICEBOX_9             239
#define IDB_CLOSE_DICEBOX_10            240
#define IDB_CLOSE_DICEBOX_2             241
#define IDB_CLOSE_DICEBOX_8             242
#define IDB_CLOSE_DICEBOX_15            243
#define IDB_CLOSE_DICEBOX_12            244
#define IDB_CLOSE_DICEBOX_13            245
#define IDB_CLOSE_DICEBOX_14            246
#define IDB_CLOSE_DICEBOX_5             247
#define IDB_CLOSE_DICEBOX_7             248
#define IDB_OPEN_DICEBOX_2              249
#define IDB_SHAKE_DICEBOX_12            250
#define IDB_SHAKE_DICEBOX_21            251
#define IDB_OPEN_DICEBOX_10             252
#define IDB_OPEN_DICEBOX_7              253
#define IDB_SHAKE_DICEBOX_17            254
#define IDB_SHAKE_DICEBOX_8             255
#define IDB_CLOSE_DICEBOX_6             256
#define IDB_OPEN_DICEBOX_1              257
#define IDB_OPEN_DICEBOX_6              258
#define IDB_SHAKE_DICEBOX_1             259
#define IDB_SHAKE_DICEBOX_10            260
#define IDB_SHAKE_DICEBOX_13            261
#define IDB_SHAKE_DICEBOX_9             262
#define IDB_OPEN_DICEBOX_11             263
#define IDB_OPEN_DICEBOX_3              264
#define IDB_OPEN_DICEBOX_5              265
#define IDB_OPEN_DICEBOX_9              266
#define IDB_SHAKE_DICEBOX_5             267
#define IDB_OPEN_DICEBOX_12             268
#define IDB_OPEN_DICEBOX_13             269
#define IDB_OPEN_DICEBOX_14             270
#define IDB_OPEN_DICEBOX_15             271
#define IDB_OPEN_DICEBOX_4              272
#define IDB_OPEN_DICEBOX_8              273
#define IDB_SHAKE_DICEBOX_6             274
#define IDB_SHAKE_DICEBOX_7             275
#define IDB_DICEBOX                     276
#define IDB_DICE                        277
#define IDB_CLOSE_DICEBOX               278
#define IDR_WAVE3                       279
#define IDB_WIN_FLAG                    280
#define IDR_PNG1                        281
#define IDB_BITMAP3                     282
#define IDB_END_SCORE_NUMBER            282
#define IDC_RECORD_LIST                 1056

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        283
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
