//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GamePlaza.rc
//
#define IDD_GAME_PLAZA                  102
#define IDD_SHORT_MESSAGE               110
#define IDD_FIND_USER                   111
#define IDD_MANAGER_RIGHT               115
#define IDR_MAINFRAME                   128
#define IDS_MAIN_TITLE                  129
#define IDD_GAME_ROOM                   130
#define IDD_LOGON                       132
#define IDR_MENU                        134
#define IDD_STATUS                      136
#define IDB_CONNECT_STATUS              137
#define IDB_SERVER_LIST_IMAGE           142
#define IDB_USER_STATUS                 144
#define IDD_OPTION                      181
#define IDD_ENTER_TABLE_PASS            182
#define IDD_OPTION_SYSTEM               183
#define IDC_HAND_CUR                    209
#define IDB_TABLE_LOCK                  230
#define IDB_TABLE_READY                 231
#define IDD_SEND_WARNING                262
#define IDD_REGISTER                    266
#define IDD_MANAGER_MESSAGE             267
#define IDD_MANAGER_SERVER              268
#define IDD_USER_INFO                   272
#define IDD_OPTION_TABLE_RULE           273
#define IDD_CUSTOM_FACE                 276
#define IDD_MODIFY_INDIVIDUAL           277
#define IDC_CHAT_MESSAGE                1004
#define IDC_TABLE_PASSWORD              1004
#define IDC_SERVER                      1005
#define IDC_ACCOUNTS                    1006
#define IDC_PASSWORD                    1007
#define IDC_REM_PASSWORD                1008
#define IDC_SPREADER                    1008
#define IDC_DELETE_RECORD               1009
#define IDC_SEND_SHORT                  1010
#define IDC_PASSWORD2                   1011
#define IDC_BIND_USER                   1011
#define IDC_NET_OPTION                  1011
#define IDC_REGISTER                    1012
#define IDC_RECV_MESSAGE                1012
#define IDC_BIND_GAME                   1012
#define IDC_LOGON_TYPE                  1013
#define IDC_SEND_MESSAGE                1013
#define IDC_NAME                        1013
#define IDC_MAIN_PAGE                   1014
#define IDC_ACCID                       1014
#define IDC_PASSWORD_PROTECT            1015
#define IDC_GET_PASSWORD                1016
#define IDC_REG_WEB                     1016
#define IDC_PROXY_TEST                  1017
#define IDC_PROXY_TYPE                  1018
#define IDC_PROXY_SERVER                1019
#define IDC_PROXY_USER                  1020
#define IDC_PROXY_PORT                  1021
#define IDC_LIST                        1022
#define IDC_PROXY_PASS                  1022
#define IDC_BORDER                      1023
#define IDC_USER_ID                     1024
#define IDC_CLOSE                       1025
#define IDC_TYPE_NAME                   1026
#define IDC_BRING_TABLE_PASSWORD        1029
#define IDC_VOR_SPLITER                 1039
#define IDC_CHAT_INPUT                  1043
#define IDC_AUTO_SIT                    1045
#define IDC_SEND_CHAT                   1046
#define IDC_EXPRESSION                  1047
#define IDC_PHRASE                      1048
#define IDC_COLOR_SET                   1049
#define IDC_CLEAN_SCREEN                1050
#define IDC_FIND_USER                   1051
#define IDC_LIMIT_IP                    1052
#define IDC_QUIT_ROOM                   1052
#define IDC_LIMIT_FLEE_RATE             1053
#define IDC_BUGLE                       1053
#define IDC_FLEE_RATE                   1054
#define IDC_BANK                        1054
#define IDC_LIMIT_SCORE                 1055
#define IDC_USER_LIST                   1056
#define IDC_LIMIT_DETEST                1060
#define IDC_LIMIT_WIN_RATE              1061
#define IDC_WIN_RATE                    1062
#define IDC_SCORE_LESS                  1063
#define IDC_SAVE_NONE                   1065
#define IDC_SAVE_ACCOUNTS               1066
#define IDC_SAVE_ACCOUNTS_AND_PASS      1067
#define IDC_CHAT_OBJECT                 1068
#define IDC_USER_FACE                   1073
#define IDC_PRIVIEW                     1074
#define IDC_WARNING_MESSAGE             1077
#define IDC_ROOM_CHAT                   1078
#define IDC_GAME_MESSAGE                1078
#define IDC_GAME_CHAT                   1079
#define IDC_ROOM_MESSAGE                1079
#define IDC_SEND_WISPER                 1080
#define IDC_SYSTEM_MESSAGE              1080
#define IDC_PLAY_GAME                   1081
#define IDC_LOOKON_GAME                 1082
#define IDC_SET_SHALL_CLOSE             1082
#define IDC_LIMIT_WISPER                1083
#define IDC_RADIO1                      1083
#define IDC_LIMIT_ROOM_CHAT             1084
#define IDC_RADIO2                      1084
#define IDC_GENDER                      1084
#define IDC_LIMIT_ENTER_GAME            1085
#define IDC_RADIO3                      1085
#define IDC_OPEN_CHAT_MESSAGE           1085
#define IDC_BROWSER                     1085
#define IDC_LIMIT_GAME_CHAT             1086
#define IDC_SHOW_INOUT                  1086
#define IDC_HOR_SPLITER                 1086
#define IDC_UPLOAD                      1086
#define IDC_SCORE_MAX                   1087
#define IDC_LIMIT_ENTER_ROOM            1087
#define IDC_ENTER_TABLE_PASSWORD        1087
#define IDC_DELETE                      1087
#define IDC_WARIMG_MSG                  1089
#define IDC_PLAZA_FACE                  1090
#define IDC_GAME_FACE                   1091
#define IDC_RESET_SHALL_CLOSE           1094
#define IDC_ALLOW_WISPER                1095
#define IDC_ALLOW_ROOM_CHAT             1096
#define IDC_ALLOW_ENTER_GAME            1097
#define IDC_ALLOW_GAME_CHAT             1098
#define IDC_BOSS_HOTKEY                 1098
#define IDC_ALLOW_ENTER_ROOM            1099
#define IDM_LOGON_PLAZA                 32772
#define IDM_CONNECT_SERVER              32774
#define IDM_CANCEL_CONNECT              32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        318
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1088
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
