//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GameClient.rc
//
#define IDR_HTML_MYLISEVIEW             103
#define IDD_GAME_FRAME                  121
#define IDD_LISTVIEWINFO                122
#define IDD_CONTROL                     122
#define IDD_SCORE                       123
#define IDD_LISTINFO                    124
#define IDC_MY_HAND                     130
#define IDB_BT_EXPESSION                140
#define IDB_BT_SEND_CHAT                141
#define IDB_BT_COLOR_SET                142
#define IDB_BT_CLEAN_SCREEN             143
#define IDB_GAME_END                    145
#define IDR_MAINFRAME                   146
#define IDC_CARD_CUR                    147
#define IDR_WAVE1                       148
#define IDB_BABY                        149
#define IDB_A_LINK                      150
#define IDB_BT_BOMB                     150
#define IDB_LINE                        151
#define IDB_BT_START                    152
#define IDB_SBABY                       154
#define IDB_BK                          155
#define IDB_READY                       156
#define IDB_BOMB                        157
#define IDB_RESET                       159
#define IDD_OPTION                      160
#define IDB_BT_RESET                    161
#define IDB_BT_RERANK                   162
#define IDR_ACCELERATOR1                163
#define IDT_LINK001                     164
#define IDT_LINK002                     165
#define IDT_LINK003                     166
#define IDT_LINK004                     167
#define IDT_LINK005                     168
#define IDT_LINK006                     169
#define IDT_LINK007                     170
#define IDT_LINK008                     171
#define IDT_LINK009                     172
#define IDT_LINK010                     173
#define IDB_BT_CLEAR                    323
#define IDB_BT_COLOR                    324
#define IDB_BT_FACE                     325
#define IDB_BT_INFO                     326
#define IDB_GAME_END_EXER               329
#define IDB_BK_LEFT                     330
#define IDB_BK_RIGHT                    331
#define IDB_BT_SEND                     332
#define IDT_BLAST001                    333
#define IDT_BLAST002                    334
#define IDT_BLAST003                    335
#define IDT_BLAST004                    336
#define IDT_BLAST005                    337
#define IDT_BLAST006                    338
#define IDT_BLAST007                    339
#define IDT_BLAST008                    340
#define IDT_BLAST009                    341
#define IDT_BLAST010                    342
#define IDT_BLAST011                    343
#define IDT_BLAST012                    344
#define IDT_BLAST013                    345
#define IDT_BLAST014                    346
#define IDT_BLAST015                    347
#define IDT_BLAST016                    348
#define IDT_BLAST017                    349
#define IDT_BLAST018                    350
#define IDT_BLAST019                    351
#define IDT_BLAST020                    352
#define IDT_BLAST021                    353
#define IDT_BLAST022                    354
#define IDT_BLAST023                    355
#define IDT_BLAST024                    356
#define IDT_BLAST025                    357
#define IDT_BLAST026                    358
#define IDT_BLAST027                    359
#define IDT_BLAST028                    360
#define IDT_BLAST029                    361
#define IDT_BLAST030                    362
#define IDT_BLAST031                    363
#define IDT_BLAST032                    364
#define IDT_BLAST033                    365
#define IDT_BLAST034                    366
#define IDT_BLAST035                    367
#define IDT_BLAST036                    368
#define IDT_BLAST037                    369
#define IDT_BLAST038                    370
#define IDT_BLAST039                    371
#define IDT_BLAST040                    372
#define IDT_BLAST041                    373
#define IDT_BLAST042                    374
#define IDT_BLAST043                    375
#define IDT_BLAST044                    376
#define IDT_BLAST045                    377
#define IDT_BLAST046                    378
#define IDT_CHESS_SMALL                 379
#define IDT_CHESS_FACE_SMALL            380
#define IDT_CHESS_FACE                  381
#define IDT_CHESS                       382
#define IDB_CHESS                       382
#define IDB_SBKT                        383
#define IDB_SBKF                        384
#define IDB_CHESS_FACE                  385
#define IDB_BT_QUIT                     386
#define IDB_BT_EXERCISE                 387
#define IDB_IMPLEMENT_BOM               388
#define IDB_IMPLEMENT_GUIDE             389
#define IDB_IMPLEMENT_RESET             390
#define IDB_TIMER_BK                    391
#define IDB_TIMER                       392
#define IDB_PARTICLE                    393
#define IDB_BT_QUIT2                    394
#define IDB_BT_ORDER                    395
#define IDB_BT_ADVISE                   396
#define IDB_BT_SET                      397
#define IDB_TEAM_A                      398
#define IDB_TEAM_B                      399
#define IDB_TEAM_FREE                   400
#define IDT_WIN                         401
#define IDT_READY                       402
#define IDT_NUMBER                      403
#define IDB_IMPLEMENT_STOPIT            404
#define IDB_FRAME_CHOOSE                405
#define IDT_STOPIT                      406
#define IDB_CHESS_PROP                  407
#define IDB_CLOG                        408
#define IDB_IMPLEMENT_CLOG              408
#define IDT_SCORE                       409
#define IDT_LOSE                        410
#define IDT_CRY                         411
#define IDT_SMALLCRY                    412
#define IDB_PROPINFO                    413
#define IDB_LLK_LOGO                    414
#define IDR_BGMIDI                      418
#define IDB_BT_SEND_CHAT_B              500
#define IDB_BT_EXPESSION_B              501
#define IDB_BT_COLOR_SET_B              502
#define IDB_BT_CLEAN_SCREEN_B           503
#define IDB_FACE                        504
#define IDB_BT_QUIT_BAR                 505
#define IDB_BT_SETTING                  506
#define IDB_BT_TAB                      507
#define IDB_BT_TALK                     508
#define IDB_BT_UP                       509
#define IDB_BT_DOWN                     510
#define IDC_ENABLE_MUSIC                1002
#define IDC_ENABLE_SOUND                1006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        417
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
